### PR TITLE
add python 3.9 build for django 2.2.x

### PR DESCRIPTION
**Pull request by ltalirz**
django 2.2.x currently has no build for python3.9
trying to add that here

### CODE REVIEW

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by ltalirz** [comment]
@astamminger I followed your suggestion and the python 3.9 build seems to run through just fine
However, appveyour and drone are not happy with this "non-mergeable pull request"...

**Comment by astamminger** [comment]
@conda-forge-admin, please restart ci

**Comment by ocefpaf** [comment]
We can ignore Appveyor here. Windows is built on Azure. Thanks all!

**Pull request merged**
