### PR TITLE
Update to 2.0.1

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@msarahan and @conda-forge/core the Linux failure here is b/c conda is preferring defaults `libkml` instead of conda-forge's version.

```
 libkml:          1.3.0-h9d32c78_3  defaults
```

Conda-forge's pins [`boost 1.65.1`](https://github.com/conda-forge/libkml-feedstock/blob/master/recipe/meta.yaml#L31) at run time, the same as defaults, but there the name is `libboost` now.

```
libboost:        1.65.1-habcd387_4 defaults
```

That kind of channel preference breakage is causing a lot of grief when using the gdal ecosystem and even if we try to maintain the same versions we are fooled by name differences. I do understand that moving the conda-build 3 is the best way to handle this but we are still far behind on that.

It would be nice if the channel preference feature actually preferred the top channel instead of conda wiggling its way out of a different set of packages.

**Comment by jakirkham** [comment]
Had the same problem recently. As @jschueller had proposed we move to `1.66.0`, ended up just doing that to fix the issue. Given there is likely a `conda` bug at play here, cc-ing @kalefranz.

**Comment by nehaljwani** [comment]
Hey guys, is [this](https://github.com/conda-forge/django-feedstock/pull/41/commits/8d7a6d6d7678079d8b8e9bc19807717f896359a8) patch still needed?

**Comment by ocefpaf** [comment]
> Hey guys, is this patch still needed?

Your mileage may vary depending on the version `defaults` and `conda-forge` have now. The issue will only go away once we move to conda-build 3.

**Pull request merged**
