### PR TITLE
Updated to 1.9.7

### PR DESCRIPTION
**Pull request by ocefpaf**
Django 1.9.8 release notes
==========================

*July 18, 2016*

Django 1.9.8 fixes a security issue and several bugs in 1.9.7.

XSS in admin's add/change related popup
=======================================

Unsafe usage of JavaScript's ``Element.innerHTML`` could result in XSS in the
admin's add/change related popup. ``Element.textContent`` is now used to
prevent execution of the data.

The debug view also used ``innerHTML``. Although a security issue wasn't
identified there, out of an abundance of caution it's also updated to use
``textContent``.

Bugfixes
========

* Fixed missing ``varchar/text_pattern_ops`` index on ``CharField`` and
  ``TextField`` respectively when using ``AddField`` on PostgreSQL
  (:ticket:`26889`).

* Fixed ``makemessages`` crash on Python 2 with non-ASCII file names
  (:ticket:`26897`).

Django 1.9.7 release notes
==========================

*June 4, 2016*

Django 1.9.7 fixes several bugs in 1.9.6.

Bugfixes
========

* Removed the need for the ``request`` context processor on the admin login
  page to fix a regression in 1.9 (:ticket:`26558`).

* Fixed translation of password validators' ``help_text`` in forms
  (:ticket:`26544`).

* Fixed a regression causing the cached template loader to crash when using
  lazy template names (:ticket:`26603`).

* Fixed ``on_commit`` callbacks execution order when callbacks make
  transactions (:ticket:`26627`).

* Fixed ``HStoreField`` to raise a ``ValidationError`` instead of crashing on
  non-dictionary JSON input (:ticket:`26672`).

* Fixed ``dbshell`` crash on PostgreSQL with an empty database name
  (:ticket:`26698`).

* Fixed a regression in queries on a ``OneToOneField`` that has ``to_field``
  and ``primary_key=True`` (:ticket:`26667`).

### CODE REVIEW

**Comment by ocefpaf** [comment]
Here is another case were `libtiff` from `defaults`, pinned to `jpeg 8*`, gets chosen even though `gdal` is pinned to `jpeg 9*` and they both get installed in the same env! That combination should be incompatible and the solution should either get `conda-forge`'s `libtiff` or just return unsatisfiable dependencies. 

Ping @pelson I cannot see a way around it besides either forcing `jpeg 9b` here, even though that is bad practice IMO b/c `jpeg 9b` is not a direct dependency of `django`, or we should update our pinning of `xz` to `5.2.*` to be equal to `defaults` and get our packages "promoted."

**Comment by ocefpaf** [comment]
`OS X` is failing b/c of the known `gdal` failure (hopefully fixed in https://github.com/conda-forge/gdal-feedstock/pull/87):

```shell
import: 'django.contrib.gis.forms'

Traceback (most recent call last):

  File "/Users/travis/miniconda3/conda-bld/test-tmp_dir/run_test.py", line 289, in <module>

    import django.contrib.gis.forms

  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/django/contrib/gis/forms/__init__.py", line 3, in <module>

    from .fields import (  # NOQA

  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/django/contrib/gis/forms/fields.py", line 4, in <module>

    from django.contrib.gis.geos import GEOSException, GEOSGeometry

  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/django/contrib/gis/geos/__init__.py", line 5, in <module>

    from .collections import (  # NOQA

  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/django/contrib/gis/geos/collections.py", line 9, in <module>

    from django.contrib.gis.geos.geometry import (

  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/django/contrib/gis/geos/geometry.py", line 10, in <module>

    from django.contrib.gis import gdal

  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/django/contrib/gis/gdal/__init__.py", line 48, in <module>

    from django.contrib.gis.gdal.driver import Driver  # NOQA

  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>

    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi

  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>

    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal

  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/django/contrib/gis/gdal/libgdal.py", line 21, in <module>

    lgdal = CDLL(os.path.join(sys.prefix, 'lib', libname))

  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/ctypes/__init__.py", line 362, in __init__

    self._handle = _dlopen(self._name, mode)

OSError: dlopen(/Users/travis/miniconda3/envs/_test/lib/libgdal.1.dylib, 6): image not found

TESTS FAILED: django-1.9.7-py27_0
```

**Comment by pelson** [comment]
> Ping @pelson I cannot see a way around it besides either forcing jpeg 9b here, even though that is bad practice IMO b/c jpeg 9b is not a direct dependency of django, or we should update our pinning of xz to 5.2.* to be equal to defaults and get our packages "promoted."

Did this get raised with conda do you know @ocefpaf? I put together an example of the resolve step picking the wrong jpeg even though I explicitly asked it not to, that is definitely a bug in conda/conda.

**Comment by ocefpaf** [comment]
> Did this get raised with conda do you know @ocefpaf? 

Nope. Feel free to do it though. Let me know if I can help.

**Pull request merged**
