### PR TITLE
update to 1.11.9

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by kwilcox** [comment]
At first glance it looks like tte gdal patch needs an update: https://github.com/conda-forge/django-feedstock/blob/django_1.11.x/recipe/libgdal.patch

Still referencing 1.10.x

**Comment by sannykr** [comment]
@kwilcox : Can I update the patch?

**Comment by kwilcox** [comment]
Of course

**Comment by sannykr** [comment]
I don't know how to do that. Is there any way you can help?

**Comment by sannykr** [comment]
@dougalsutherland : Is there any way you can help me here? It seems the patch needs to be updated.

**Comment by kwilcox** [comment]
I'm re-running the build. I believe this was fixed upstream.

**Comment by sannykr** [comment]
@kwilcox : Thanks. I really appreciate that.

**Comment by kwilcox** [comment]
I'm fixing...

**Comment by kwilcox** [comment]
see https://github.com/conda-forge/django-feedstock/pull/42

**Pull request closed without merging**
