### PR TITLE
Django 1.7.11

### PR DESCRIPTION
**Pull request by astamminger**
Hi @ocefpaf @kwilcox,

and here the Django==1.7.11 recipe. Had to disable the build for python3 entirely, because HTMLParseError is removed for python >=3.5 crashing the tests.

Best,
Andreas

### CODE REVIEW

**Comment by ocefpaf** [comment]
Looks like Windows is not happy with some of the file names there.

**Comment by astamminger** [comment]
When extracting the archive Windows complains about some files for which it cannot create symlinks (Exactly those files reported in the error logs) Don't know if this is also the reason to make the build fail. I'll have a look this afternoon!

**Comment by ocefpaf** [comment]
If you don't care about Windows we can merge this as-is though.

**Comment by astamminger** [comment]
> 
> 
> If you don't care about Windows we can merge this as-is though.

Tried it on my local Windows box where it builds just fine. However, there were some issues with the patches under Windows (geos version is found as ``3.6.2-CAPI-1.10.2 999999`` and gdal is ``gdal202.dll``). I would suggest to try it once more with these changes together with ``-vvv`` for the setup to possibly get some more info and see what happens. If this doesn't help: I couldn't care less about Windows.

**Comment by ocefpaf** [comment]
>  If this doesn't help: I couldn't care less about Windows.

Then... Merge?

**Pull request merged**
