### PR TITLE
django 2.2.12

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Thanks for getting the LTS branch going!

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
travis ppc fail was:
```
docker: write /var/lib/docker/tmp/GetImageBlob432932299: no space left on device.
```

not sure what to do about this: apparently there's a way to ask for it to be done on azure...

**Comment by astamminger** [comment]
@conda-forge-admin, please restart ci

**Comment by astamminger** [comment]
thanks a lot @bollwyvl :+1:

**Pull request merged**
